ps_project_homepage:
    path:     /
    defaults: { _controller: PSProjectBundle:Project:viewListProject }
    
ps_project_add_project:  
    path:     /addproject
    defaults: { _controller: PSProjectBundle:Project:addProject }    
    
ps_project_view_project:  
    path:     /{keyproject}/{idproject}
    defaults: { _controller: PSProjectBundle:Project:viewProject }   
    
    
    


ps_project_delete_participant_ajax:
    path:     /{keyproject}/{idproject}/deleteparticipant/{idparticipant}
    defaults: { _controller: PSProjectBundle:Participant:deleteParticipant }    

ps_project_add_participant:  
    path:     /{keyproject}/{idproject}/addparticipant
    defaults: { _controller: PSProjectBundle:Participant:addParticipant }  
    
    
    
    
ps_project_add_information:  
    path:     /{keyproject}/{idproject}/addinformation
    defaults: { _controller: PSProjectBundle:Information:addInformation }   
    
    
ps_project_statut_information:  
    path:     /{keyproject}/{idproject}/{idinformation}/{statut}
    defaults: { _controller: PSProjectBundle:Information:statutInformation }   
    
    
    
    
    
ps_project_add_article:  
    path:     /{keyproject}/{idproject}/addarticle
    defaults: { _controller: PSProjectBundle:Article:addArticle }   
    
    
ps_project_edit_article:  
    path:     /{keyproject}/{idproject}/{idarticle}
    defaults: { _controller: PSProjectBundle:Article:editArticle }   