ps_project_homepage:
    path:     /
    defaults: { _controller: PSProjectBundle:Project:viewListProject }
    
ps_project_view_project_admin:  
    path:     /listprojectadmin
    defaults: { _controller: PSProjectBundle:Project:viewListProjectAdmin }  
    
ps_project_edit_participant_admin:  
    path:     /{keyproject}/{idproject}/{idparticipant}/editprojectadmin
    defaults: { _controller: PSProjectBundle:Participant:editParticipantAdmin } 
    
    
    
ps_project_contact:  
    path:     /contact
    defaults: { _controller: PSProjectBundle:Contact:viewContact }   

    

    
    
ps_project_add_project:  
    path:     /addproject
    defaults: { _controller: PSProjectBundle:Project:addProject }    
    
ps_project_view_project:  
    path:     /{keyproject}/{idproject}
    defaults: { _controller: PSProjectBundle:Project:viewProject }   
    

    
ps_project_edit_project:  
    path:     /{keyproject}/{idproject}/editproject
    defaults: { _controller: PSProjectBundle:Project:editProject }       
    
ps_project_delete_project:  
    path:     /{keyproject}/{idproject}/deleteproject
    defaults: { _controller: PSProjectBundle:Project:deleteProject }       
    
    
    
    
    
ps_project_view_participant:  
    path:     /{keyproject}/{idproject}/viewparticipant
    defaults: { _controller: PSProjectBundle:Participant:viewParticipant }      

ps_project_delete_participant_ajax:
    path:     /{keyproject}/{idproject}/deleteparticipant/{idparticipant}
    defaults: { _controller: PSProjectBundle:Participant:deleteParticipant }    

ps_project_add_participant:  
    path:     /{keyproject}/{idproject}/addparticipant
    defaults: { _controller: PSProjectBundle:Participant:addParticipant }  
    
ps_project_edit_participant:  
    path:     /{keyproject}/{idproject}/{idparticipant}/editparticipant
    defaults: { _controller: PSProjectBundle:Participant:editParticipant }      
    
    
    

    
    
    
    
    
ps_project_add_article:  
    path:     /{keyproject}/{idproject}/addarticle
    defaults: { _controller: PSProjectBundle:Article:addArticle }   
    
ps_project_delete_article:  
    path:     /{keyproject}/{idproject}/{idarticle}/deletearticle
    defaults: { _controller: PSProjectBundle:Article:deleteArticle }   
    
ps_project_edit_article:  
    path:     /{keyproject}/{idproject}/{idarticle}/article
    defaults: { _controller: PSProjectBundle:Article:editArticle }   
    
    
    
    
    
    
ps_project_add_information:  
    path:     /{keyproject}/{idproject}/addinformation
    defaults: { _controller: PSProjectBundle:Information:addInformation }   
    
    
ps_project_statut_information:  
    path:     /{keyproject}/{idproject}/{idinformation}/{statut}
    defaults: { _controller: PSProjectBundle:Information:statutInformation }   

    
