ps_project_homepage:
    path:     /
    defaults: { _controller: PSProjectBundle:Project:viewListProject }
    
ps_project_add_porject:  
    path:     /addproject
    defaults: { _controller: PSProjectBundle:Project:addProject }    
    
ps_project_view_project:  
    path:     /{keyproject}
    defaults: { _controller: PSProjectBundle:Project:viewProject }   